const host =
  process.env.NODE_ENV === "development"
    ? "http://localhost:3000"
    : "https://groove-music-clone.vercel.app";

export const data = [
  {
    id: 458,
    title: "Midnight Groove",
    web: "www.musicstore.com",
    artist: "The Night Owls",
    genre: "Funk",
    duration: "3:55",
    album: "After Hours",
    src: `${host}/assets/audio/audio.mp3`,
  },
  {
    id: 2,
    title: "Echoes in the Wind",
    web: "www.musicstore.com",
    artist: "Melancholy Breeze",
    genre: "Ambient",
    duration: "6:20",
    album: "Whispers of Nature",
    src: `${host}/assets/audio/audio-2.mp3`,
  },
  {
    id: 3,
    title: "Summer Breeze",
    web: "www.musicstore.com",
    artist: "Sunny Days Band",
    genre: "Pop",
    duration: "4:10",
    album: "Sunshine Vibes",
    src: `${host}/assets/audio/audio.mp3`,
  },
  {
    id: 4,
    title: "Electric Dreams",
    web: "www.musicstore.com",
    artist: "Neon Nights",
    genre: "Electronic",
    duration: "3:45",
    album: "Synthwave Dreams",
    src: `${host}/assets/audio/audio-2.mp3`,
  },
  {
    id: 5,
    title: "Moonlit Sonata",
    web: "www.musicstore.com",
    artist: "Lunar Symphony",
    genre: "Classical",
    duration: "5:30",
    album: "Night Serenades",
    src: `${host}/assets/audio/audio.mp3`,
  },
  {
    id: 6,
    title: "Gypsy Rhapsody",
    web: "www.musicstore.com",
    artist: "Roving Troubadours",
    genre: "World",
    duration: "4:55",
    album: "Wanderlust Journeys",
    src: `${host}/assets/audio/audio-2.mp3`,
  },
  {
    id: 7,
    title: "City Lights",
    web: "www.musicstore.com",
    artist: "Urban Symphony",
    genre: "Pop",
    duration: "3:30",
    album: "Metropolitan Melodies",
    src: `${host}/assets/audio/audio.mp3`,
  },
  {
    id: 8,
    title: "Jungle Rhythms",
    web: "www.musicstore.com",
    artist: "Tropic Beats",
    genre: "World",
    duration: "4:40",
    album: "Wilderness Echoes",
    src: `${host}/assets/audio/audio-2.mp3`,
  },
  {
    id: 9,
    title: "Ocean Serenade",
    web: "www.musicstore.com",
    artist: "Seaside Symphony",
    genre: "Ambient",
    duration: "5:15",
    album: "Coastal Harmony",
    src: `${host}/assets/audio/audio.mp3`,
  },
  {
    id: 10,
    title: "Neon Nights",
    web: "www.musicstore.com",
    artist: "Retro Wave Crew",
    genre: "Synthwave",
    duration: "4:30",
    album: "Electric Dreams",
    src: `${host}/assets/audio/audio-2.mp3`,
  },
  {
    id: 11,
    title: "Whispers in the Dark",
    web: "www.musicstore.com",
    artist: "Nocturnal Melodies",
    genre: "Gothic",
    duration: "4:45",
    album: "Shadows Within",
    src: `${host}/assets/audio/audio.mp3`,
  },
  {
    id: 12,
    title: "Echoes of Tomorrow",
    web: "www.musicstore.com",
    artist: "Future Soundtrack",
    genre: "Electronic",
    duration: "3:55",
    album: "Tech Fusion",
    src: `${host}/assets/audio/audio-2.mp3`,
  },
  {
    id: 13,
    title: "Melodic Whispers",
    web: "www.musicstore.com",
    artist: "Harmonic Echoes",
    genre: "Ambient",
    duration: "4:20",
    album: "Enigmatic Dreams",
    src: `${host}/assets/audio/audio.mp3`,
  },
  {
    id: 14,
    title: "Celestial Harmony",
    web: "www.musicstore.com",
    artist: "Stellar Soundscape",
    genre: "New Age",
    duration: "3:50",
    album: "Cosmic Serenity",
    src: `${host}/assets/audio/audio-2.mp3`,
  },
  {
    id: 15,
    title: "Ethereal Echo",
    web: "www.musicstore.com",
    artist: "Mystic Melodies",
    genre: "Ambient",
    duration: "5:10",
    album: "Whispering Enchantment",
    src: `${host}/assets/audio/audio.mp3`,
  },
  {
    id: 16,
    title: "Serendipity Sonata",
    web: "www.musicstore.com",
    artist: "Harmony Ensemble",
    genre: "Classical",
    duration: "4:45",
    album: "Symphonic Serenity",
    src: `${host}/assets/audio/audio-2.mp3`,
  },
];
